### ISSUE TITLE
how to evaluate the metrics KL,CC,NSS,AUC

### ISSUE THREAD

**Issue by Biotan** [remega/OMCNN_2CLSTM#9]
thanks for your works,if it's possible ,could you please give us the evaluate code ,it will be really appreciated .

**Comment by remega** [comment]
You can find the matlab and pthon codes at https://github.com/cvzoya/saliency/tree/master/code_forMetrics and https://github.com/tarunsharma1/saliency_metrics

**Comment by Biotan** [comment]
OK，thanks a lot
